module.exports = {
  siteMetadata: {
    htmlLang: "en",
    contenLang: "en-us",
    title: "Nyxo Help Center",
    titleTemplate: "%s · Nyxo Help Center",
    description: "",
    siteUrl: "https://help.nyxo.app",
    siteName: "A Help Center Theme for Nyxo",
    logoUrl: "/images/logo.png",
    logoLabel: "Help Center",
    searchText: "Search",
    faviconUrl: "/images/favicon.png",
    socialSharingImageUrl: "/images/social-sharing-preview.png",
    twitter: "@helloNyxo",
    facebookUrl: "https://www.facebook.com/helloNyxo",
    ctaButtonText: "Open Nyxo.app",
    ctaButtonUrl: "https://nyxo.app",
    linkText: "Go to nyxo.app",
    linkUrl: "https://nyxo.app",
    headline: "How can we be helpful?",
    footerText: "Back to main website",
    footerUrl: "https://nyxo.app",
    googleTagManagerId: "",
    googleAnalyticsMeasurementId: "",
    contentLang: "en"
  },
  plugins: ["gatsby-plugin-typescript", "@mlent/gatsby-theme-help-center"],
};
